// Taxonomia muscular canônica usada pelo app inteiro (dados, treino e mapa anatômico).
// Toda fonte externa (ExerciseDB, free-exercise-db) é normalizada para estes IDs.
export const MUSCLE_IDS = [
  'neck',
  'traps',
  'shoulders',
  'rear_delts',
  'chest',
  'biceps',
  'triceps',
  'forearms',
  'abs',
  'obliques',
  'lats',
  'upper_back',
  'lower_back',
  'glutes',
  'quads',
  'hamstrings',
  'adductors',
  'abductors',
  'calves',
] as const

export type MuscleId = (typeof MUSCLE_IDS)[number]

export const MUSCLE_LABELS_PT: Record<MuscleId, string> = {
  neck: 'Pescoço',
  traps: 'Trapézio',
  shoulders: 'Deltoides',
  rear_delts: 'Deltoide posterior',
  chest: 'Peitoral',
  biceps: 'Bíceps',
  triceps: 'Tríceps',
  forearms: 'Antebraço',
  abs: 'Abdômen',
  obliques: 'Oblíquos',
  lats: 'Dorsal (Latíssimo)',
  upper_back: 'Costas superior',
  lower_back: 'Lombar',
  glutes: 'Glúteos',
  quads: 'Quadríceps',
  hamstrings: 'Posterior de coxa',
  adductors: 'Adutores',
  abductors: 'Abdutores',
  calves: 'Panturrilha',
}

/**
 * Normaliza nomes de músculos vindos de fontes externas (ExerciseDB, free-exercise-db,
 * variações em inglês/português) para o MuscleId canônico. Chaves em minúsculas.
 */
const MUSCLE_ALIASES: Record<string, MuscleId> = {
  neck: 'neck',
  pescoço: 'neck',
  traps: 'traps',
  trapezius: 'traps',
  trapézio: 'traps',
  'levator scapulae': 'traps',
  shoulders: 'shoulders',
  delts: 'shoulders',
  deltoids: 'shoulders',
  deltoide: 'shoulders',
  deltoides: 'shoulders',
  'rear delts': 'rear_delts',
  'serratus anterior': 'chest',
  chest: 'chest',
  pectorals: 'chest',
  peitoral: 'chest',
  biceps: 'biceps',
  bíceps: 'biceps',
  triceps: 'triceps',
  tríceps: 'triceps',
  forearms: 'forearms',
  'lower arms': 'forearms',
  antebraço: 'forearms',
  abs: 'abs',
  abdominals: 'abs',
  abdômen: 'abs',
  waist: 'abs',
  obliques: 'obliques',
  oblíquos: 'obliques',
  lats: 'lats',
  latissimus: 'lats',
  dorsal: 'lats',
  back: 'upper_back',
  'upper back': 'upper_back',
  'middle back': 'upper_back',
  spine: 'lower_back',
  'lower back': 'lower_back',
  lombar: 'lower_back',
  glutes: 'glutes',
  glúteos: 'glutes',
  quads: 'quads',
  quadriceps: 'quads',
  quadríceps: 'quads',
  'upper legs': 'quads',
  hamstrings: 'hamstrings',
  'posterior de coxa': 'hamstrings',
  adductors: 'adductors',
  adutores: 'adductors',
  abductors: 'abductors',
  abdutores: 'abductors',
  calves: 'calves',
  'lower legs': 'calves',
  panturrilha: 'calves',
}

export function normalizeMuscleName(raw: string): MuscleId | null {
  const key = raw.trim().toLowerCase()
  return MUSCLE_ALIASES[key] ?? null
}
